services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jennida-hotel-web
    restart: always
    ports:
      - "5110:3000"
    environment:
      DATABASE_URL: "postgresql://hotel_admin:hotel_password@postgres:5432/hotel_db?schema=public"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
    depends_on:
      - postgres
    networks:
      - app-internal

  postgres:
    image: postgres:15-alpine
    container_name: jennida-hotel-postgres
    restart: always
    environment:
      POSTGRES_USER: hotel_admin
      POSTGRES_PASSWORD: hotel_password
      POSTGRES_DB: hotel_db
    volumes:
      - hotel_pgdata:/var/lib/postgresql/data
    networks:
      - app-internal

volumes:
  hotel_pgdata:

networks:
  app-internal:
    driver: bridge
